I'm sorry, but an uncaught exception occurred.

While running game code:
  File "ErogeFrameworkTester/_TownExplorer_Tester.rpy", line 7, in script call
    call Initialize__Protagonist
  File "ErogeFrameworkTester/GameFiles/Characters/Protagonist.rpy", line 3, in script
    $ protagonist = person.Developed_Character().build("PROTAGONIST", names_system.Character_Names().build(standard_name = "Jim", standard_possessive = "Jim's", first = "James", first_possessive = "James'", last = "Clearing", last_possessive = "Clearing's"), fundamentals.Gender.MALE, 25)
  File "ErogeFrameworkTester/GameFiles/Characters/Protagonist.rpy", line 3, in <module>
    $ protagonist = person.Developed_Character().build("PROTAGONIST", names_system.Character_Names().build(standard_name = "Jim", standard_possessive = "Jim's", first = "James", first_possessive = "James'", last = "Clearing", last_possessive = "Clearing's"), fundamentals.Gender.MALE, 25)
Exception: ERROR: Character_Names.build(): Can't build name 'Jim'. Name already in database.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "ErogeFrameworkTester/_TownExplorer_Tester.rpy", line 7, in script call
    call Initialize__Protagonist
  File "ErogeFrameworkTester/GameFiles/Characters/Protagonist.rpy", line 3, in script
    $ protagonist = person.Developed_Character().build("PROTAGONIST", names_system.Character_Names().build(standard_name = "Jim", standard_possessive = "Jim's", first = "James", first_possessive = "James'", last = "Clearing", last_possessive = "Clearing's"), fundamentals.Gender.MALE, 25)
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "ErogeFrameworkTester/GameFiles/Characters/Protagonist.rpy", line 3, in <module>
    $ protagonist = person.Developed_Character().build("PROTAGONIST", names_system.Character_Names().build(standard_name = "Jim", standard_possessive = "Jim's", first = "James", first_possessive = "James'", last = "Clearing", last_possessive = "Clearing's"), fundamentals.Gender.MALE, 25)
  File "PowerPlayFramework/Characters/Character_NamesPy.py", line 151, in build
  File "renpy/exports.py", line 2494, in error
    _error_handlers[-1](msg)
  File "renpy/exports.py", line 2471, in _error
    raise Exception(msg)
Exception: ERROR: Character_Names.build(): Can't build name 'Jim'. Name already in database.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
FreeCitiesSlaver 0.1
Sun Jun 20 15:49:29 2021
